### PR TITLE
TypeScript implementation

### PR DESCRIPTION
**Pull request by jgaehring**
This should represent all the main features for the implementation, to eventually resolve datafoodconsortium/connector-typescript#4, except for a few outstanding issues:

1. __Failing to import several interfaces__, such as `IPerson`, `ISocialMedia`, and `IPhoneNumber`, into classes `Agent`, `Enterprise`, etc. These seem to coincide with the features added in [2.1.0](https://github.com/datafoodconsortium/data-model-uml/blob/v2.1.0/CHANGELOG.md#210---2023-11-06), or maybe that's just a red herring.
2. __Misaligned types for getters in `DefinedProducts`__, specifically getters for multiple properties that implement subclasses of `ICharacteristic`, such as `getPhysicalCharacteristics`, `getAllergenCharacteristics`. I haven't identified any others. Possibly something to do with the `ISKOSConcept`, which also seems to be having some issues getting imported correctly for the interface definitions.
3. __No tests yet__, and also need to find a good way to test the prefix mappings to the semantic IRI's (e.g., `"dfc-b:Catalog"`).

Regarding those prefix mappings, I see that the PHP semantizer does have a [`setPrefix`](https://github.com/assemblee-virtuelle/semantizer-php/blob/6e470d70fe3a7c7e1baf4966e27e25b5e8645695/src/Semantizer.php#L109-L115) method that sets it for the connector:

https://github.com/datafoodconsortium/connector-codegen/blob/c177f39c80f6f7e3c71566e65caabd52afa175d5/src/org/datafoodconsortium/connector/codegen/php/static/src/Connector.php#L17-L21

But as far as I can tell, there's no such analog yet in the TypeScript semantizer.

I'm leaving this as a draft for now until those issues are resolved or worked around, but if easier to address them in the meantime by marking it for review, @lecoqlibre or @RaggedStaff, please go ahead!

### CODE REVIEW

**Comment by jgaehring** [comment]
> 2\. **Misaligned types for getters in `DefinedProducts`**, specifically getters for multiple properties that implement subclasses of `ICharacteristic`, such as `getPhysicalCharacteristics`, `getAllergenCharacteristics`. I haven't identified any others. Possibly something to do with the `ISKOSConcept`, which also seems to be having some issues getting imported correctly for the interface definitions.

I fixed the underlying issues here, which I believe did stem from changes in [2.0.0](https://github.com/datafoodconsortium/data-model-uml/blob/v2.0.0/CHANGELOG.md#200---2023-10-03). This leads me to think if first issue listed above, regarding imports for interfaces like `ISocialMedia` and `IMainContactOwner`, may indeed be related to the changes in [2.1.0](https://github.com/datafoodconsortium/data-model-uml/blob/v2.1.0/CHANGELOG.md#210---2023-11-06).

I found that a similar issue, where `ISKOSConcept` failed to be imported and `SKOSConcept` was imported instead. I was able to remedy this in `product.uml`, where I changed the href from the id for `SKOSConcept` to `ISKOSConcept` (jgaehring/data-model-uml@2e78e7e):

```diff
-      <elementImport xmi:id="_SQ0AwOqNEeyCo6a7S9M9vA">
-        <importedElement xmi:type="uml:Class" href="skos.uml#_XhC24E2LEe2Pq5gmFYw1MQ"/>
+      <elementImport xmi:id="_6HIqYE76Ee2TpoYuSsmzTA">
+        <importedElement xmi:type="uml:Interface" href="skos.uml#_r06YgE1mEe2Pq5gmFYw1MQ"/>
```

I feel I'm starting to exceed my proper understanding of the UML model and don't want to be introducing changes like this without additional feedback. I'll see what headway I can make with the last issue, regarding tests, but will mark this ready for review so that others can suggest improvements.

**Review by lecoqlibre — CHANGES_REQUESTED** [review]
Thanks for your work @jgaehring.

I wrote some queries to automatically import what's needed. This will ease the generator code and also the UML model like it was proposed here https://github.com/datafoodconsortium/connector-codegen/discussions/16.

I would need push access to your fork @jgaehring in order to add my commits to this PR, could you allow me? For docs see [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

I was able to run (failing) tests.

Here are some more tasks that need to be handled:
- [x] Auto-imports (I should be allowed to push my commits to this PR)
- [x] https://github.com/datafoodconsortium/data-model-uml/issues/12 (I can take it)
- [x] https://github.com/datafoodconsortium/data-model-uml/issues/13 (I can take it)
- [ ] Abstract sub classes should not re-implement methods already implemented in parents (like some methods in `Agent` sub classes).
- [ ] Old references to static context should be replaced with https://www.datafoodconsortium.org (in the `Connector` class and in tests)

**Comment by jgaehring** [comment]
Oh great, all those points make sense. Thanks, @lecoqlibre! :pray:

> would need push access to your fork in order to add my commits to this PR, could you allow me?

I believe this is enabled now? If you have difficulty pushing to it let me know.

> Old references to static context should be replaced with https://www.datafoodconsortium.org (in the `Connector` class and in tests)

Ah, yes I saw this in the original TS codegen when I tried to run the tests there too and wondered. I can do a quick search and replace easily enough and push that up first.


> Abstract sub classes should not re-implement methods already implemented in parents (like some methods in `Agent` sub classes).

Got it, I think I can fix that easily enough.

**Comment by jgaehring** [comment]
Here's the commit with the substitutions I made for `static.datafoodconsortium.org`: jgaehring/connector-codegen@92f8218

**Comment by jgaehring** [comment]
I'm having a devil of a time with the tests. There are likely other issues (see * below), but a major hindrance seems to be related to the Jest test runner itself and using ECMAScript Modules instead of CommonJS, which seems linked to use of the [`NODE_OPTIONS=--experimental-vm-modules`](https://nodejs.org/dist/latest-v20.x/docs/api/cli.html#--experimental-vm-modules) environment variable. This seems to be blocked by an open issue in Node itself. It's been open for a few years and there are some workarounds, but I'm still not sure I see what would work for our case, if that even is the problem. Here are the relevant issues:

- https://github.com/jestjs/jest/issues/11434
- https://github.com/nodejs/node/issues/37648
- https://github.com/oas-tools/oas-tools/pull/366

Here's what the error message looks for one of the tests. Note it refers to a line `698`, which is line [533](https://github.com/jestjs/jest/blob/22267424a824310779bad3cafaae59485ce2a6c7/packages/jest-runtime/src/index.ts#L530) in the source, from the `jest-runtime` library.

```
 FAIL  test/Address.test.js
  ● Test suite failed to run

    request for './body.js' is not yet fulfilled

      at Runtime.linkAndEvaluateModule (node_modules/jest-runtime/build/index.js:698:5)


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/Address.test.js.
```

Have you encountered anything like this, @lecoqlibre?

\* = The other issue I referred to is an error that reads `"IRIs can not be mapped to other IRIs"`, which I suspect is related to some of our previous discussions around IRIs, but I'm hesitant to begin diagnosing that problem until the issues with Jest are resolved. As it is, the IRIs error only appears sporadically, depending on whether the issue with Node ESM imports throws an exception or not, which is not ideal for debugging.

**Comment by lecoqlibre** [comment]
> Have you encountered anything like this, @lecoqlibre?

Yes absolutely, same here. I encountered this issue in the previous version of the TS connector. I think I found a workaround but don't know if it can work for the new version and the evolution of Jest. Are you familiar with other test framework that we might use instead of Jest?

> The other issue I referred to is an error that reads "IRIs can not be mapped to other IRIs"

I think it's related to the prefixes we are now using in the connector. I'm working on the Semantizer to add a `setContext` method like you suggested (instead of `setPrefix`).

**Comment by jgaehring** [comment]
> Are you familiar with other test framework that we might use instead of Jest?

Actually, I've just about got the native Node.js [test runner](https://nodejs.org/dist/latest-v20.x/docs/api/test.html#test-runner) working. It was introduced with Node v.18 (LTS) back in 2022, so it's stable.

I was about ready to say I fixed it, but I wanted to try it out with a clean build of the generated code, and now I'm seeing some weird syntax errors in the generated TypeScript. I haven't changed anything on the Acceleo side, just the static files in `typescript/static/test/` and the static `package.json` file. I'll report back when I figure it out, hopefully soon! :crossed_fingers:

**Comment by jgaehring** [comment]
Oh, and I've got one more commit I'm not pushing onto this branch just yet, b/c I didn't want to muddy the waters any further, but I removed some unnecessary `async` keywords, since they might interfere with the test runner or cause it to time out or something unexpected. Probably a best practice for either [Jest](https://jestjs.io/docs/asynchronous#asyncawait) or the [Node test runner](https://nodejs.org/dist/latest-v20.x/docs/api/test.html#extraneous-asynchronous-activity). Here are the diffs:

https://github.com/jgaehring/connector-codegen/compare/typescript...jgaehring:connector-codegen:async-tests

**Comment by lecoqlibre** [comment]
My last commit [edaf89f](https://github.com/datafoodconsortium/connector-codegen/pull/20/commits/edaf89fb8afd849e68a8414ea90729ab4e67d4bc) integrates the dev (alpha.3) version of [Semantizer](https://github.com/assemblee-virtuelle/semantizer-typescript). I changed the Semantizer dependency type to a GitHub repo, this way we can run `npm update @virtual-assembly/semantizer` every time changes are made.

@jgaehring I also updated dependencies of `rdf-ext`.

Also, note that we should use the UML model from the [next branch](https://github.com/datafoodconsortium/data-model-uml/tree/next) of the data-model-uml repo when generating.

I merged your commits about using `node:test` and without some unnecessary async. I got all the tests passing except the ones for the import feature and the remover methods. For now we should comment the remover tests and expect Exceptions. I'm looking at how to fix the import tests. I think it's related to the context.

As the Semantizer has now a dedicated class which act like an environment, we should move in the future some components from the connector to the Semantizer (like I did for the PHP version). Especially import/export, store, factories.

**Comment by jgaehring** [comment]
I've got a start at the test generation ([2c8507a](https://github.com/datafoodconsortium/connector-codegen/pull/20/commits/2c8507af85919862669ef8a989bb2679f553dc78)). So far I'm just testing the constructor. There are a total of 109 tests with 99 passing and 10 failing. I've put the relevant tests and the full results up on this gist:

https://gist.github.com/jgaehring/bde27fe6991a289cc7016ed77bc1120e

There seem to be three kinds of errors that I'm not yet sure how to resolve:

1. Duplicate import statements, as in `Enterprise.test.js`, or missing imports, as in `QuantitativeValue.test.js`
2. Unknown ontology type in `PlannedConsumptionFlow.test.js`, which may be related to the `Flow` superclass or the `ConnectorFactory`, based on the stacktrace.
3. A weird issue where a plain string ends up as the test value for images in `SuppliedProduct.test.js`, which results in a `images.forEach is not a function` error b/c it should expect an array of strings. The generated PHP tests also has a plain string for the `imates` property, so maybe this is something to do with how the test values are generated?

I have to put this down for now, might not be able to pick it back up til later this week. It's taken me a bit longer than anticipated (what else is new), but if these issues can be knocked out, hopefully the getters and setters will follow in short order. :crossed_fingers:

**Comment by RaggedStaff** [comment]
@lecoqlibre / @jgaehring is this ready to merge ?

**Comment by lecoqlibre** [comment]
Yep I did not get a response from Jamie so I fixed the Changelog. I think we will have to add other details in the Changelog when we will be releasing the next version to really track all the work that have been done with this PR.

**Comment by jgaehring** [comment]
Oh hey! Sorry, I was tracking down where those updates to the CHANGELOG got lost. The branching history got a little wonky with some squashed commits and then when I introduced 50f48ee56fdd0d72e3e2e78141188150aad98cf9, but I _think_ I'd resolved it from my fork. I wasn't 💯 sure it addressed the missing updates you were referring to, @lecoqlibre, so thanks for fixing and merging! And copy that w/r/t updating the CHANGELOG more fully before the next version gets tagged.

Otherwise, there is still the lingering issue of incomplete test generation. This was incompletely addressed with datafoodconsortium/connector-typescript#13. Apart from resolving the errors in the constructor tests, as mentioned above in https://github.com/datafoodconsortium/connector-codegen/pull/20#issuecomment-2030820144 and documented in [this gist](https://gist.github.com/jgaehring/bde27fe6991a289cc7016ed77bc1120e), the tests for getters and setters are also lacking.

Perhaps it's worth opening two new issues, then: 1) fix the errors in the constructor tests, and 2) generate tests for getters and setters. What say ye, @RaggedStaff, @lecoqlibre, @RachL? Can discuss tmw, too, at datafoodconsortium/datafoodconsortium#5.

**Pull request merged**
